name: '49thGroup, LLC'
favicon: null
layout_spectrum: 0.3458781
typography_spectrum: 1
title: Home
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00070d'
    - '#fefefe'
    - '#c19f22'
    - '#fbd931'
    - '#7a6111'
  brandStrength: 0.3180557803716511
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.4416998
purpose: []
