name: '49thGroup, LLC'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21986959571950138
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00070d'
    - '#fefefe'
    - '#c19f22'
    - '#fbd931'
    - '#7a6111'
  brandStrength: 0.31805578037165105
  lightness: 0
  saturation: 0.9780008369125426
  rhythmicContrast: 0.4416998326778412
purpose: []
