title: Home
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9780008369125426
  brandStrength: 0.3180557803716511
  rhythmicContrast: 0.4416998326778412
  brandColors:
    - '#00070d'
    - '#fefefe'
    - '#c19f22'
    - '#fbd931'
    - '#7a6111'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: '49thGroup, LLC'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2198695957195014
layout_spectrum: 0.3458781
